--======================================================
--Creación de usuario.
create user CarCenter identified by qwe123;
alter session set "_ORACLE_SCRIPT"=true;
GRANT DBA TO CarCenter;
--AGREGAR CAMPO DESCUENTO A LA TABLA REPUESTOS.
ALTER TABLE REPUESTOS ADD DESCUENTO NUMBER(3,2);
--Agregar Campo Presupuesto a TABLA CLIENTE.
ALTER TABLE CLIENTES ADD PRESUPUESTO NUMBER(*,0) DEFAULT 0 NOT NULL;
--Insertar datos a la tabla REPUESTOS.
INSERT INTO REPUESTOS (CODIGO,NOMBRE_REPUESTO,PRECIO_UNITARIO,UNIDADES_INVENTARIO,PROVEEDOR,DESCUENTO) VALUES (1,'Espejos',50400,256,'Coches', 0.3);
INSERT INTO REPUESTOS (CODIGO,NOMBRE_REPUESTO,PRECIO_UNITARIO,UNIDADES_INVENTARIO,PROVEEDOR,DESCUENTO) VALUES (2,'Filtro de aceite',13596,591,'Coches', 0.18);
INSERT INTO REPUESTOS (CODIGO,NOMBRE_REPUESTO,PRECIO_UNITARIO,UNIDADES_INVENTARIO,PROVEEDOR,DESCUENTO) VALUES (3,'Aceite de motor',24356,134,'Coches', 0.142);
INSERT INTO REPUESTOS (CODIGO,NOMBRE_REPUESTO,PRECIO_UNITARIO,UNIDADES_INVENTARIO,PROVEEDOR,DESCUENTO) VALUES (4,'Bomba de combustible',244449,69,'Coches',0.499);
INSERT INTO REPUESTOS (CODIGO,NOMBRE_REPUESTO,PRECIO_UNITARIO,UNIDADES_INVENTARIO,PROVEEDOR,DESCUENTO) VALUES (5,'Filtro hidraulico',188789,127,'Coches', 0.12);
INSERT INTO REPUESTOS (CODIGO,NOMBRE_REPUESTO,PRECIO_UNITARIO,UNIDADES_INVENTARIO,PROVEEDOR,DESCUENTO) VALUES (6,'Velocimetro',1234122,348,'Coches', 0);

--Insertar datos a la tabla REPUESTOS_X_MANTENIMIENTOS.
INSERT INTO REPUESTOS_X_MANTENIMIENTOS (CODIGO, UNIDADES, TIEMPO_ESTIMADO, COD_MANTENIMIENTO, COD_REPUESTO) VALUES (1, 3, 2, 4, 6);
INSERT INTO REPUESTOS_X_MANTENIMIENTOS (CODIGO, UNIDADES, TIEMPO_ESTIMADO, COD_MANTENIMIENTO, COD_REPUESTO) VALUES (2, 2, 1, 13, 1);