create or replace PROCEDURE  SPFACTURACION
(
  pDocumento IN INTEGER,
  pCursorMtto OUT SYS_REFCURSOR,        --Retorna información del cliente, mecanico y Mtto.
  pCursorServicios OUT SYS_REFCURSOR,   --Retorna información de lo servicios por mtto.
  pCursorRepuestos OUT SYS_REFCURSOR    --Retorna información de los srvicios por mtto.
) AS
-- =============================================
-- Author:         Jorge Giovanni Sanabria
-- Create date:    28 de Febrero 2020
-- Description:    Resultado de facturación para un cliente de CAR CENTER.
-- =============================================
    
BEGIN
    OPEN pCursorMtto FOR
       SELECT CL.PRIMER_NOMBRE || ' ' || CL.SEGUNDO_NOMBRE CLNOMBRES, CL.PRIMER_APELLIDO || ' ' || CL.SEGUNDO_APELLIDO CLAPELLIDOS, CL.TIPO_DOCUMENTO, 
       CL.CELULAR, CL.DIRECCION, CL.EMAIL, MN.CODIGO, MN.FECHA, 
       MC.PRIMER_NOMBRE || ' ' || MC.SEGUNDO_NOMBRE MCNOMBRES, MC.PRIMER_APELLIDO || ' ' || MC.SEGUNDO_APELLIDO MCAPELLIDOS, MC.TIPO_DOCUMENTO, MC.DOCUMENTO, 
       MC.CELULAR, MC.DIRECCION, MC.EMAIL, MC.ESTADO, CL.PRESUPUESTO
       FROM CLIENTES CL
       INNER JOIN VEHICULOS VH ON VH.CLI_DOCUMENTO = CL.DOCUMENTO
       INNER JOIN MANTENIMIENTOS MN ON MN.COD_PLACA = VH.PLACA
       INNER JOIN MECANICOS MC ON MC.DOCUMENTO = MN.MEC_DOCUMENTO
       WHERE CL.DOCUMENTO = pDocumento AND MN.ESTADO = 4;
       
    OPEN pCursorServicios FOR
       SELECT MN.CODIGO, SR.NOMBRE_SERVICIO, SR.PRECIO
       FROM CLIENTES CL
       INNER JOIN VEHICULOS VH ON VH.CLI_DOCUMENTO = CL.DOCUMENTO
       INNER JOIN MANTENIMIENTOS MN ON MN.COD_PLACA = VH.PLACA
       INNER JOIN MECANICOS MC ON MC.DOCUMENTO = MN.MEC_DOCUMENTO
       INNER JOIN SERVICIOS_X_MANTENIMIENTOS SM ON SM.COD_MANTENIMIENTO = MN.CODIGO
       INNER JOIN SERVICIOS SR ON SR.CODIGO = SM.COD_SERVICIO
       WHERE CL.DOCUMENTO = pDocumento AND MN.ESTADO = 4;
       
    OPEN pCursorRepuestos FOR
       SELECT MN.CODIGO, RP.NOMBRE_REPUESTO, RP.PRECIO_UNITARIO, RM.UNIDADES, RP.DESCUENTO
       FROM CLIENTES CL
       INNER JOIN VEHICULOS VH ON VH.CLI_DOCUMENTO = CL.DOCUMENTO
       INNER JOIN MANTENIMIENTOS MN ON MN.COD_PLACA = VH.PLACA
       INNER JOIN MECANICOS MC ON MC.DOCUMENTO = MN.MEC_DOCUMENTO
       INNER JOIN REPUESTOS_X_MANTENIMIENTOS RM ON RM.COD_MANTENIMIENTO = MN.CODIGO
       INNER JOIN REPUESTOS RP ON RP.CODIGO = RM.COD_REPUESTO
       WHERE CL.DOCUMENTO = pDocumento AND MN.ESTADO = 4;

EXCEPTION WHEN OTHERS THEN
  raise_application_error(-20001, SQLCODE || ': Un error ha ocurrido generando la facturación del documento: '|| pDocumento ||'  -ERROR: '|| sqlerrm );

  ROLLBACK;
END SPFACTURACION;